apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprogram-deployment
  labels:
    app: myprogram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myprogram
  template:
    metadata:
      labels:
        app: myprogram
    spec:
      containers:
      - name: mycontainer
        image: docker.io/medamine97/myprogram:latest
        args: ["-u", "https://news.ycombinator.com", "-o","json"]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"