apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprogram-deployment
  labels:
    app: myprogram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myprogram
  template:
    metadata:
      labels:
        app: myprogram
    spec:
      containers:
      - name: mycontainer
        image: docker.io/medamine97/myprogram:latest
        command: ["python3", "myprogram.py"]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /config
          name: config-volume
        - mountPath: /data
          name: myprogram-storage
        - mountPath: /secrets
          name: secret-volume
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: myprogram-config
      - name: myprogram-storage
        persistentVolumeClaim:
          claimName: myprogram-pvc
      - name: secret-volume
        secret:
          secretName: myprogram-secret