apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprogram-deployment
  labels:
    app: myprogram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myprogram
  template:
    metadata:
      labels:
        app: myprogram
    spec:
      containers:
      - name: mycontainer
        image: docker.io/medamine97/myprogram:latest
        command: ["python3", "myprogram.py"]
        args: ["-u", "https://www.google.com", "-o","csv", "-f", "/data/output.csv"]
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /data
          name: myprogram-storage
      volumes:
      - name: myprogram-storage
        persistentVolumeClaim:
          claimName: myprogram-pvc