name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myprogram:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Install OCI CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install oci-cli

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        echo "[DEFAULT]" > ~/.oci/config
        echo "user=${{ secrets.OCI_USER }}" >> ~/.oci/config
        echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
        echo "tenancy=${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
        echo "region=${{ secrets.OCI_REGION }}" >> ~/.oci/config
        echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config 
      
    - name: Get cluster-info
      run: |
        kubectl get cluster-info

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f myprogram-deployment.yaml --validate=false
    
    - name: Get deployment & pod status
      run: |
        kubectl get deployment myprogram-deployment
        kubectl get pods -l app=myprogram
