name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myprogram:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker tag myprogram:latest ${{ secrets.DOCKER_USERNAME }}/myprogram:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      run: |
        sudo apt-get update
        sudo apt-get install -y kubectl

    - name: Set up kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config 
      
    - name: Get nodes
      run: |
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f myprogram-deployment.yaml --validate=false
    
    - name: Get deployment & pod status
      run: |
        kubectl get deployment myprogram-deployment
        kubectl get pods -l app=myprogram
